export default function sitemap() {
  return [
    {
      url: 'https://seefunnel.com',
      lastModified: new Date(),
      changeFrequency: 'daily',
      priority: 1,
    },
    {
      url: 'https://seefunnel.com/about',
      lastModified: new Date(),
      changeFrequency: 'daily',
      priority: 0.8,
    },
    {
      url: 'https://seefunnel.com/pricing',
      lastModified: new Date(),
      changeFrequency: 'daily',
      priority: 0.8,
    },
    {
      url: 'https://seefunnel.com/contact-us',
      lastModified: new Date(),
      changeFrequency: 'daily',
      priority: 0.8,
    },
    {
      url: 'https://seefunnel.com/howitworks',
      lastModified: new Date(),
      changeFrequency: 'daily',
      priority: 0.8,
    },
    {
      url: 'https://seefunnel.com/blogs',
      lastModified: new Date(),
      changeFrequency: 'daily',
      priority: 0.8,
    },
    {
      url: 'https://seefunnel.com/view/113',
      lastModified: new Date(),
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://seefunnel.com/view/114',
      lastModified: new Date(),
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://seefunnel.com/view/115',
      lastModified: new Date(),
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://seefunnel.com/view/119',
      lastModified: new Date(),
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://seefunnel.com/view/120',
      lastModified: new Date(),
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://seefunnel.com/view/121',
      lastModified: new Date(),
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://seefunnel.com/view/122',
      lastModified: new Date(),
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://seefunnel.com/view/123',
      lastModified: new Date(),
      changeFrequency: 'weekly',
      priority: 0.8,
    }, 
    {
      url: 'https://seefunnel.com/view/124',
      lastModified: new Date(),
      changeFrequency: 'weekly',
      priority: 0.8,
    }, 
    {
      url: 'https://seefunnel.com/view/125',
      lastModified: new Date(),
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://seefunnel.com/view/127',
      lastModified: new Date(),
      changeFrequency: 'weekly',
      priority: 0.8,
    }, 
    {
      url: 'https://seefunnel.com/view/128',
      lastModified: new Date(),
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://seefunnel.com/view/129',
      lastModified: new Date(),
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://seefunnel.com/view/130',
      lastModified: new Date(),
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://seefunnel.com/view/131',
      lastModified: new Date(),
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://seefunnel.com/view/132',
      lastModified: new Date(),
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://seefunnel.com/view/134',
      lastModified: new Date(),
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://seefunnel.com/view/133',
      lastModified: new Date(),
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://seefunnel.com/view/135',
      lastModified: new Date(),
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://seefunnel.com/view/136',
      lastModified: new Date(),
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://seefunnel.com/view/137',
      lastModified: new Date(),
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://seefunnel.com/view/138',
      lastModified: new Date(),
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://seefunnel.com/view/139',
      lastModified: new Date(),
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://seefunnel.com/view/140',
      lastModified: new Date(),
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://seefunnel.com/view/141',
      lastModified: new Date(),
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://seefunnel.com/view/142',
      lastModified: new Date(),
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://seefunnel.com/view/143',
      lastModified: new Date(),
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://seefunnel.com/view/144',
      lastModified: new Date(),
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://seefunnel.com/view/145',
      lastModified: new Date(),
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://seefunnel.com/view/146',
      lastModified: new Date(),
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://seefunnel.com/view/147',
      lastModified: new Date(),
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://seefunnel.com/view/148',
      lastModified: new Date(),
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://seefunnel.com/people/jonathan-tuttle-RYIK47R',
      lastModified: new Date(),
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://seefunnel.com/people/john-plattenberger-44WZW8Q',
      lastModified: new Date(),
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://seefunnel.com/people/joseph-campos-7YJHZDL',
      lastModified: new Date(),
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://seefunnel.com/people/kendell-kauffeldt-Y3RIL40',
      lastModified: new Date(),
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://seefunnel.com/people/kathy-navlyt-KEWOODV',
      lastModified: new Date(),
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://seefunnel.com/people/karimah-bennett-PFLNZZM',
      lastModified: new Date(),
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://seefunnel.com/people/john-ledoux-DJXE2GV',
      lastModified: new Date(),
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://seefunnel.com/people/joel-perrego-91WGN1A',
      lastModified: new Date(),
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://seefunnel.com/people/judy-keyes-J0JPU49',
      lastModified: new Date(),
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://seefunnel.com/people/joelle-irons-Q20UUP5',
      lastModified: new Date(),
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://seefunnel.com/people/keith-merritt-8SQSXEA',
      lastModified: new Date(),
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://seefunnel.com/people/karen-polyasko-R2UFA1O',
      lastModified: new Date(),
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://seefunnel.com/people/karen-saintlot-B34WKPI',
      lastModified: new Date(),
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
          url: 'https://seefunnel.com/people/katherine-burr-QZBVRZ0',
          lastModified: new Date(),
          changeFrequency: 'weekly',
          priority: 0.8,
    },
    {
          url: 'https://seefunnel.com/people/john-shutak-6T3X58V',
          lastModified: new Date(),
          changeFrequency: 'weekly',
          priority: 0.8,
    },
    {
          url: 'https://seefunnel.com/people/joleen-williams-02I4131',
          lastModified: new Date(),
          changeFrequency: 'weekly',
          priority: 0.8,
    },
    {
          url: 'https://seefunnel.com/people/joseph-abousaid-KNRI7JF',
          lastModified: new Date(),
          changeFrequency: 'weekly',
          priority: 0.8,
    },
    {
          url: 'https://seefunnel.com/people/justin-nash-WS4GFDT',
          lastModified: new Date(),
          changeFrequency: 'weekly',
          priority: 0.8,
    },
    {
          url: 'https://seefunnel.com/people/kate-waters-ZAY9NK7',
          lastModified: new Date(),
          changeFrequency: 'weekly',
          priority: 0.8,
    },
    {
          url: 'https://seefunnel.com/people/june-parsons-6BVX8L3',
          lastModified: new Date(),
          changeFrequency: 'weekly',
          priority: 0.8,
    },
    {
          url: 'https://seefunnel.com/people/john-mitterling-WJH72CW',
          lastModified: new Date(),
          changeFrequency: 'weekly',
          priority: 0.8,
    },
    {
          url: 'https://seefunnel.com/people/josh-powell-FP16JV6',
          lastModified: new Date(),
          changeFrequency: 'weekly',
          priority: 0.8,
    },
    {
          url: 'https://seefunnel.com/people/judith-heath-0DB74JH',
          lastModified: new Date(),
          changeFrequency: 'weekly',
          priority: 0.8,
    },
    {
          url: 'https://seefunnel.com/people/kendra-pope-5JR6D1O',
          lastModified: new Date(),
          changeFrequency: 'weekly',
          priority: 0.8,
    },
    {
          url: 'https://seefunnel.com/people/keoni-denison-PS0WIRF',
          lastModified: new Date(),
          changeFrequency: 'weekly',
          priority: 0.8,
    },
    {
          url: 'https://seefunnel.com/people/katherine-christie-VFQ3R2G',
          lastModified: new Date(),
          changeFrequency: 'weekly',
          priority: 0.8,
    },
    {
          url: 'https://seefunnel.com/people/katy-kranze-H7Q3VFV',
          lastModified: new Date(),
          changeFrequency: 'weekly',
          priority: 0.8,
    },
    {
          url: 'https://seefunnel.com/people/julie-chambers-LWWCDPB',
          lastModified: new Date(),
          changeFrequency: 'weekly',
          priority: 0.8,
    },
    {
          url: 'https://seefunnel.com/people/joel-helms-E1BWXE7',
          lastModified: new Date(),
          changeFrequency: 'weekly',
          priority: 0.8,
    },
    {
      url: 'https://seefunnel.com/people/joshua-henderson-DU6YIBT',
      lastModified: new Date(),
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://seefunnel.com/people/julie-chortanoff-JRUR8SV',
      lastModified: new Date(),
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
          url: 'https://seefunnel.com/people/keegan-jindra-UN2P3AW',
          lastModified: new Date(),
          changeFrequency: 'weekly',
          priority: 0.8,
    },
    {
          url: 'https://seefunnel.com/people/joshua-bodary-XSP08NX',
          lastModified: new Date(),
          changeFrequency: 'weekly',
          priority: 0.8,
    },
    {
          url: 'https://seefunnel.com/people/kaylee-felix-RFJPYMC',
          lastModified: new Date(),
          changeFrequency: 'weekly',
          priority: 0.8,
    },
    {
          url: 'https://seefunnel.com/people/kathy-mcvaney-HJ1TR8D',
          lastModified: new Date(),
          changeFrequency: 'weekly',
          priority: 0.8,
    },
    {
          url: 'https://seefunnel.com/people/john-edgington-EGWEIKR',
          lastModified: new Date(),
          changeFrequency: 'weekly',
          priority: 0.8,
    },
    {
          url: 'https://seefunnel.com/people/jon-abels-N3E32ZF',
          lastModified: new Date(),
          changeFrequency: 'weekly',
          priority: 0.8,
    },
    {
          url: 'https://seefunnel.com/people/kenneth-tyson-GRUU4DW',
          lastModified: new Date(),
          changeFrequency: 'weekly',
          priority: 0.8,
    },
    {
          url: 'https://seefunnel.com/people/julie-raphael-6Q5ADZD',
          lastModified: new Date(),
          changeFrequency: 'weekly',
          priority: 0.8,
    },
    {
          url: 'https://seefunnel.com/people/kaley-mansour-MQURE9N',
          lastModified: new Date(),
          changeFrequency: 'weekly',
          priority: 0.8,
    },
    {
          url: 'https://seefunnel.com/people/katie-smart-BCF47LC',
          lastModified: new Date(),
          changeFrequency: 'weekly',
          priority: 0.8,
    },
    {
          url: 'https://seefunnel.com/people/jordyn-chambers-5ODDV6S',
          lastModified: new Date(),
          changeFrequency: 'weekly',
          priority: 0.8,
    },
    {
          url: 'https://seefunnel.com/people/justin-hime-FNPLBYF',
          lastModified: new Date(),
          changeFrequency: 'weekly',
          priority: 0.8,
    },
    {
          url: 'https://seefunnel.com/people/katie-dallstream-EPKN17A',
          lastModified: new Date(),
          changeFrequency: 'weekly',
          priority: 0.8,
    },
    {
          url: 'https://seefunnel.com/people/ken-overby-ZDR0Y8W',
          lastModified: new Date(),
          changeFrequency: 'weekly',
          priority: 0.8,
    },
    {
          url: 'https://seefunnel.com/people/kathleen-nunnally-W58LK52',
          lastModified: new Date(),
          changeFrequency: 'weekly',
          priority: 0.8,
    },
    {
          url: 'https://seefunnel.com/people/joseph-springs-XD3J0WH',
          lastModified: new Date(),
          changeFrequency: 'weekly',
          priority: 0.8,
    },
    {
          url: 'https://seefunnel.com/people/kaitlin-ragone-C85G3IA',
          lastModified: new Date(),
          changeFrequency: 'weekly',
          priority: 0.8,
    },
    {
          url: 'https://seefunnel.com/people/john-carlee-XPZCSY7',
          lastModified: new Date(),
          changeFrequency: 'weekly',
          priority: 0.8,
    },
    {
          url: 'https://seefunnel.com/people/katie-catlett-2DZT24O',
          lastModified: new Date(),
          changeFrequency: 'weekly',
          priority: 0.8,
    },
    {
          url: 'https://seefunnel.com/people/kenny-marion-TC5UN9Y',
          lastModified: new Date(),
          changeFrequency: 'weekly',
          priority: 0.8,
    },
    {
          url: 'https://seefunnel.com/people/kathryn-stansbury-Q5EJ0BU',
          lastModified: new Date(),
          changeFrequency: 'weekly',
          priority: 0.8,
    },
    {
          url: 'https://seefunnel.com/people/kathy-corsochase-99916AC',
          lastModified: new Date(),
          changeFrequency: 'weekly',
          priority: 0.8,
    },
    {
          url: 'https://seefunnel.com/people/john-ihnatolya-9BYVZ9Y',
          lastModified: new Date(),
          changeFrequency: 'weekly',
          priority: 0.8,
    },
    {
          url: 'https://seefunnel.com/people/kelly-dawson-PCUJ2MT',
          lastModified: new Date(),
          changeFrequency: 'weekly',
          priority: 0.8,
    },
    {
          url: 'https://seefunnel.com/people/joy-avila-1TAPSZ5',
          lastModified: new Date(),
          changeFrequency: 'weekly',
          priority: 0.8,
    },
    {
          url: 'https://seefunnel.com/people/justin-sebastian-0DY637T',
          lastModified: new Date(),
          changeFrequency: 'weekly',
          priority: 0.8,
    },
    {
          url: 'https://seefunnel.com/people/joe-lucas-24MER0Q',
          lastModified: new Date(),
          changeFrequency: 'weekly',
          priority: 0.8,
    },
    {
          url: 'https://seefunnel.com/people/kent-thompson-2RFQ25U',
          lastModified: new Date(),
          changeFrequency: 'weekly',
          priority: 0.8,
    },
    {
          url: 'https://seefunnel.com/people/jonathan-merryman-4F4M9XH',
          lastModified: new Date(),
          changeFrequency: 'weekly',
          priority: 0.8,
    },
    {
          url: 'https://seefunnel.com/people/john-friedl-ROVQ88V',
          lastModified: new Date(),
          changeFrequency: 'weekly',
          priority: 0.8,
    },
    {
          url: 'https://seefunnel.com/people/katherine-flowers-PCGJ7H5',
          lastModified: new Date(),
          changeFrequency: 'weekly',
          priority: 0.8,
    },
    {
          url: 'https://seefunnel.com/people/katherine-zyra-MQBFBUH',
          lastModified: new Date(),
          changeFrequency: 'weekly',
          priority: 0.8,
    },
    {
          url: 'https://seefunnel.com/people/joshua-conner-RB4QEEH',
          lastModified: new Date(),
          changeFrequency: 'weekly',
          priority: 0.8,
    },
    {
          url: 'https://seefunnel.com/people/jonathan-krecicki-3J3C98M',
          lastModified: new Date(),
          changeFrequency: 'weekly',
          priority: 0.8,
    },
    {
          url: 'https://seefunnel.com/people/josie-eatmon-W4T012D',
          lastModified: new Date(),
          changeFrequency: 'weekly',
          priority: 0.8,
    },
    {
          url: 'https://seefunnel.com/people/julie-paul-FQL9YYJ',
          lastModified: new Date(),
          changeFrequency: 'weekly',
          priority: 0.8,
    },
    {
          url: 'https://seefunnel.com/people/kelly-kuhn-1KRI1VC',
          lastModified: new Date(),
          changeFrequency: 'weekly',
          priority: 0.8,
    },
    {
          url: 'https://seefunnel.com/people/john-turner-REFED87',
          lastModified: new Date(),
          changeFrequency: 'weekly',
          priority: 0.8,
    },
    {
          url: 'https://seefunnel.com/people/katie-heineman-WAFUDK4',
          lastModified: new Date(),
          changeFrequency: 'weekly',
          priority: 0.8,
    },
    {
          url: 'https://seefunnel.com/people/kari-fotis-YTOGSMG',
          lastModified: new Date(),
          changeFrequency: 'weekly',
          priority: 0.8,
    },
    {
          url: 'https://seefunnel.com/people/karen-magge-C1J5GFZ',
          lastModified: new Date(),
          changeFrequency: 'weekly',
          priority: 0.8,
    },
    {
          url: 'https://seefunnel.com/people/kayla-wisecollins-4YTAHDJ',
          lastModified: new Date(),
          changeFrequency: 'weekly',
          priority: 0.8,
    },
    {
          url: 'https://seefunnel.com/people/kaileigh-west-KDV1PAL',
          lastModified: new Date(),
          changeFrequency: 'weekly',
          priority: 0.8,
    },
    {
          url: 'https://seefunnel.com/people/keith-flynn-QMNJ8PJ',
          lastModified: new Date(),
          changeFrequency: 'weekly',
          priority: 0.8,
    },
    {
          url: 'https://seefunnel.com/people/keith-wolf-IHPUDHM',
          lastModified: new Date(),
          changeFrequency: 'weekly',
          priority: 0.8,
    },
    {
          url: 'https://seefunnel.com/people/kenneth-bowers-JFZCONN',
          lastModified: new Date(),
          changeFrequency: 'weekly',
          priority: 0.8,
    },
    {
          url: 'https://seefunnel.com/people/kelsey-pratt-AV76A1O',
          lastModified: new Date(),
          changeFrequency: 'weekly',
          priority: 0.8,
    },
    {
          url: 'https://seefunnel.com/people/josette-roten-MBXALXC',
          lastModified: new Date(),
          changeFrequency: 'weekly',
          priority: 0.8,
    },
    {
          url: 'https://seefunnel.com/people/julie-sayers-7N0SI8G',
          lastModified: new Date(),
          changeFrequency: 'weekly',
          priority: 0.8,
    },
    {
          url: 'https://seefunnel.com/people/karen-holt-SYPO5VO',
          lastModified: new Date(),
          changeFrequency: 'weekly',
          priority: 0.8,
    },
    {
          url: 'https://seefunnel.com/people/john-constantelos-D4X11VU',
          lastModified: new Date(),
          changeFrequency: 'weekly',
          priority: 0.8,
    },
    {
          url: 'https://seefunnel.com/people/jon-agaton-HVC0FT7',
          lastModified: new Date(),
          changeFrequency: 'weekly',
          priority: 0.8,
    },
    {
          url: 'https://seefunnel.com/people/justine-wiggins-FQATWCO',
          lastModified: new Date(),
          changeFrequency: 'weekly',
          priority: 0.8,
    },
    {
          url: 'https://seefunnel.com/people/john-williamson-G3MZAOW',
          lastModified: new Date(),
          changeFrequency: 'weekly',
          priority: 0.8,
    },
    {
      url: 'https://seefunnel.com/people/kara-cox-NUOMA33',
      lastModified: new Date(),
      changeFrequency: 'weekly',
      priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/kathleen-marshall-ARU00OA',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/kearns-lowman-YA2PEQJ',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/john-strizzi-MGJFD6P',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/john-stamm-3H6LVSE',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/ken-perry-0U1Y5TN',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/keith-kelly-MBKM4D6',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/june-getzinger-PE633LJ',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/kelly-friesen-XVZ7REU',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/katrina-naylor-J71WS05',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/keith-parker-P6PAT46',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/katie-shelton-T9WZY0X',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/keisha-ragsdale-L4AVZ6G',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/kelly-palmatier-P2QSDEX',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/joseph-bridges-6LNHTA0',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/kelly-hunsucker-JCPCYMC',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/karthikeyan-ananthan-6OPAA07',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/kelly-holdbrooks-2T8GGLQ',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/julie-richardson-EWP28M6',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/kelsey-rogers-EOOL68X',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/julie-carrow-LXDZAG3',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/joyce-blum-733YMZ5',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/kendra-martin-7WVAINA',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/kelly-holland-QKCSKJZ',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/kelly-nichols-CLZU47V',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/kathy-giddings-ZZEAFC4',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/joe-ely-5K0KX5E',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/julius-scott-GXEX4TI',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/josh-farmer-TCE5RR4',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/jon-widdifield-WAU2UM7',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/johanna-mercado-WXO0NEG',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/kayleigh-cook-F1THI6A',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/kathryn-sweeney-I74Q1LY',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/joshua-mason-JC17RT2',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/kara-yates-9W7W4J6',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/katie-lamotta-X7L1BYP',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/joshua-schutt-Q74BF1I',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/jordan-newsome-NXOHVUQ',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/jorge-r-KR77P3N',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/jon-robb-ALF65DX',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/jonathan-burger-VO8IM96',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/jonathan-beam-XUN5QF5',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/jonathan-moore-T7K6LK9',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/joey-kitchens-VKCXIUD',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/john-gavigan-P8NNIAS',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/justin-king-TA1AGMW',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/karen-howell-TQIJAHC',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/joe-staples-T5RG3BV',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/kate-lague-ZCINQ49',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/joyce-burke-CMHXEFR',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/joseph-conde-4G5RD20',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/kenny-boggess-G6HBKTV',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/john-lynch-V9ISQXO',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/john-land-30DBSGK',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/kelly-katterhagen-0SZ45J9',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/jordan-pulido-6MN222X',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/kathy-simmons-2AMXTVG',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/katheryn-peterson-6Z56W5F',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/kaylan-mariano-F2YGSO4',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/kayce-johnson-HZILWIA',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/john-holmes-DF3AL7P',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/jordan-sprouse-F8C7F0J',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/kelli-stoup-UXWDBA7',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/keirstin-gavalas-VEK4N43',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },    
    // {
    //   url: 'https://yourdomain.com/changes',
    //   lastModified: new Date(),
    //   changeFrequency: 'daily',
    //   priority: 0.8,
    // },
    // Add more routes dynamically if needed
    // Example with dynamic routes:
    // {
    //   url: 'https://yourdomain.com/products/product-slug',
    //   lastModified: new Date(),
    // }
  ]
}