export default function sitemap() {
  return [
    {
      url: 'https://seefunnel.com',
      lastModified: new Date(),
      changeFrequency: 'daily',
      priority: 1,
    },
    {
      url: 'https://seefunnel.com/about',
      lastModified: new Date(),
      changeFrequency: 'daily',
      priority: 0.8,
    },
    {
      url: 'https://seefunnel.com/pricing',
      lastModified: new Date(),
      changeFrequency: 'daily',
      priority: 0.8,
    },
    {
      url: 'https://seefunnel.com/contact-us',
      lastModified: new Date(),
      changeFrequency: 'daily',
      priority: 0.8,
    },
    {
      url: 'https://seefunnel.com/howitworks',
      lastModified: new Date(),
      changeFrequency: 'daily',
      priority: 0.8,
    },
    {
      url: 'https://seefunnel.com/blogs',
      lastModified: new Date(),
      changeFrequency: 'daily',
      priority: 0.8,
    },
    {
      url: 'https://seefunnel.com/view/113',
      lastModified: new Date(),
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://seefunnel.com/view/114',
      lastModified: new Date(),
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://seefunnel.com/view/115',
      lastModified: new Date(),
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://seefunnel.com/view/119',
      lastModified: new Date(),
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://seefunnel.com/view/120',
      lastModified: new Date(),
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://seefunnel.com/view/121',
      lastModified: new Date(),
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://seefunnel.com/view/122',
      lastModified: new Date(),
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://seefunnel.com/view/123',
      lastModified: new Date(),
      changeFrequency: 'weekly',
      priority: 0.8,
    }, 
    {
      url: 'https://seefunnel.com/view/124',
      lastModified: new Date(),
      changeFrequency: 'weekly',
      priority: 0.8,
    }, 
    {
      url: 'https://seefunnel.com/view/125',
      lastModified: new Date(),
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://seefunnel.com/view/127',
      lastModified: new Date(),
      changeFrequency: 'weekly',
      priority: 0.8,
    }, 
    {
      url: 'https://seefunnel.com/view/128',
      lastModified: new Date(),
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://seefunnel.com/view/129',
      lastModified: new Date(),
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://seefunnel.com/view/130',
      lastModified: new Date(),
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://seefunnel.com/view/131',
      lastModified: new Date(),
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://seefunnel.com/view/132',
      lastModified: new Date(),
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://seefunnel.com/view/134',
      lastModified: new Date(),
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://seefunnel.com/view/133',
      lastModified: new Date(),
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://seefunnel.com/view/135',
      lastModified: new Date(),
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://seefunnel.com/view/136',
      lastModified: new Date(),
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://seefunnel.com/view/137',
      lastModified: new Date(),
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://seefunnel.com/view/138',
      lastModified: new Date(),
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://seefunnel.com/view/139',
      lastModified: new Date(),
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://seefunnel.com/view/140',
      lastModified: new Date(),
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://seefunnel.com/view/141',
      lastModified: new Date(),
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://seefunnel.com/view/142',
      lastModified: new Date(),
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://seefunnel.com/view/143',
      lastModified: new Date(),
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://seefunnel.com/view/144',
      lastModified: new Date(),
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://seefunnel.com/view/145',
      lastModified: new Date(),
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://seefunnel.com/view/146',
      lastModified: new Date(),
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://seefunnel.com/view/147',
      lastModified: new Date(),
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://seefunnel.com/view/148',
      lastModified: new Date(),
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://seefunnel.com/people/jonathan-tuttle-RYIK47R',
      lastModified: new Date(),
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://seefunnel.com/people/john-plattenberger-44WZW8Q',
      lastModified: new Date(),
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://seefunnel.com/people/joseph-campos-7YJHZDL',
      lastModified: new Date(),
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://seefunnel.com/people/kendell-kauffeldt-Y3RIL40',
      lastModified: new Date(),
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://seefunnel.com/people/kathy-navlyt-KEWOODV',
      lastModified: new Date(),
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://seefunnel.com/people/karimah-bennett-PFLNZZM',
      lastModified: new Date(),
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://seefunnel.com/people/john-ledoux-DJXE2GV',
      lastModified: new Date(),
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://seefunnel.com/people/joel-perrego-91WGN1A',
      lastModified: new Date(),
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://seefunnel.com/people/judy-keyes-J0JPU49',
      lastModified: new Date(),
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://seefunnel.com/people/joelle-irons-Q20UUP5',
      lastModified: new Date(),
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://seefunnel.com/people/keith-merritt-8SQSXEA',
      lastModified: new Date(),
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://seefunnel.com/people/karen-polyasko-R2UFA1O',
      lastModified: new Date(),
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://seefunnel.com/people/karen-saintlot-B34WKPI',
      lastModified: new Date(),
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
          url: 'https://seefunnel.com/people/katherine-burr-QZBVRZ0',
          lastModified: new Date(),
          changeFrequency: 'weekly',
          priority: 0.8,
    },
    {
          url: 'https://seefunnel.com/people/john-shutak-6T3X58V',
          lastModified: new Date(),
          changeFrequency: 'weekly',
          priority: 0.8,
    },
    {
          url: 'https://seefunnel.com/people/joleen-williams-02I4131',
          lastModified: new Date(),
          changeFrequency: 'weekly',
          priority: 0.8,
    },
    {
          url: 'https://seefunnel.com/people/joseph-abousaid-KNRI7JF',
          lastModified: new Date(),
          changeFrequency: 'weekly',
          priority: 0.8,
    },
    {
          url: 'https://seefunnel.com/people/justin-nash-WS4GFDT',
          lastModified: new Date(),
          changeFrequency: 'weekly',
          priority: 0.8,
    },
    {
          url: 'https://seefunnel.com/people/kate-waters-ZAY9NK7',
          lastModified: new Date(),
          changeFrequency: 'weekly',
          priority: 0.8,
    },
    {
          url: 'https://seefunnel.com/people/june-parsons-6BVX8L3',
          lastModified: new Date(),
          changeFrequency: 'weekly',
          priority: 0.8,
    },
    {
          url: 'https://seefunnel.com/people/john-mitterling-WJH72CW',
          lastModified: new Date(),
          changeFrequency: 'weekly',
          priority: 0.8,
    },
    {
          url: 'https://seefunnel.com/people/josh-powell-FP16JV6',
          lastModified: new Date(),
          changeFrequency: 'weekly',
          priority: 0.8,
    },
    {
          url: 'https://seefunnel.com/people/judith-heath-0DB74JH',
          lastModified: new Date(),
          changeFrequency: 'weekly',
          priority: 0.8,
    },
    {
          url: 'https://seefunnel.com/people/kendra-pope-5JR6D1O',
          lastModified: new Date(),
          changeFrequency: 'weekly',
          priority: 0.8,
    },
    {
          url: 'https://seefunnel.com/people/keoni-denison-PS0WIRF',
          lastModified: new Date(),
          changeFrequency: 'weekly',
          priority: 0.8,
    },
    {
          url: 'https://seefunnel.com/people/katherine-christie-VFQ3R2G',
          lastModified: new Date(),
          changeFrequency: 'weekly',
          priority: 0.8,
    },
    {
          url: 'https://seefunnel.com/people/katy-kranze-H7Q3VFV',
          lastModified: new Date(),
          changeFrequency: 'weekly',
          priority: 0.8,
    },
    {
          url: 'https://seefunnel.com/people/julie-chambers-LWWCDPB',
          lastModified: new Date(),
          changeFrequency: 'weekly',
          priority: 0.8,
    },
    {
          url: 'https://seefunnel.com/people/joel-helms-E1BWXE7',
          lastModified: new Date(),
          changeFrequency: 'weekly',
          priority: 0.8,
    },
    {
      url: 'https://seefunnel.com/people/joshua-henderson-DU6YIBT',
      lastModified: new Date(),
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://seefunnel.com/people/julie-chortanoff-JRUR8SV',
      lastModified: new Date(),
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
          url: 'https://seefunnel.com/people/keegan-jindra-UN2P3AW',
          lastModified: new Date(),
          changeFrequency: 'weekly',
          priority: 0.8,
    },
    {
          url: 'https://seefunnel.com/people/joshua-bodary-XSP08NX',
          lastModified: new Date(),
          changeFrequency: 'weekly',
          priority: 0.8,
    },
    {
          url: 'https://seefunnel.com/people/kaylee-felix-RFJPYMC',
          lastModified: new Date(),
          changeFrequency: 'weekly',
          priority: 0.8,
    },
    {
          url: 'https://seefunnel.com/people/kathy-mcvaney-HJ1TR8D',
          lastModified: new Date(),
          changeFrequency: 'weekly',
          priority: 0.8,
    },
    {
          url: 'https://seefunnel.com/people/john-edgington-EGWEIKR',
          lastModified: new Date(),
          changeFrequency: 'weekly',
          priority: 0.8,
    },
    {
          url: 'https://seefunnel.com/people/jon-abels-N3E32ZF',
          lastModified: new Date(),
          changeFrequency: 'weekly',
          priority: 0.8,
    },
    {
          url: 'https://seefunnel.com/people/kenneth-tyson-GRUU4DW',
          lastModified: new Date(),
          changeFrequency: 'weekly',
          priority: 0.8,
    },
    {
          url: 'https://seefunnel.com/people/julie-raphael-6Q5ADZD',
          lastModified: new Date(),
          changeFrequency: 'weekly',
          priority: 0.8,
    },
    {
          url: 'https://seefunnel.com/people/kaley-mansour-MQURE9N',
          lastModified: new Date(),
          changeFrequency: 'weekly',
          priority: 0.8,
    },
    {
          url: 'https://seefunnel.com/people/katie-smart-BCF47LC',
          lastModified: new Date(),
          changeFrequency: 'weekly',
          priority: 0.8,
    },
    {
          url: 'https://seefunnel.com/people/jordyn-chambers-5ODDV6S',
          lastModified: new Date(),
          changeFrequency: 'weekly',
          priority: 0.8,
    },
    {
          url: 'https://seefunnel.com/people/justin-hime-FNPLBYF',
          lastModified: new Date(),
          changeFrequency: 'weekly',
          priority: 0.8,
    },
    {
          url: 'https://seefunnel.com/people/katie-dallstream-EPKN17A',
          lastModified: new Date(),
          changeFrequency: 'weekly',
          priority: 0.8,
    },
    {
          url: 'https://seefunnel.com/people/ken-overby-ZDR0Y8W',
          lastModified: new Date(),
          changeFrequency: 'weekly',
          priority: 0.8,
    },
    {
          url: 'https://seefunnel.com/people/kathleen-nunnally-W58LK52',
          lastModified: new Date(),
          changeFrequency: 'weekly',
          priority: 0.8,
    },
    {
          url: 'https://seefunnel.com/people/joseph-springs-XD3J0WH',
          lastModified: new Date(),
          changeFrequency: 'weekly',
          priority: 0.8,
    },
    {
          url: 'https://seefunnel.com/people/kaitlin-ragone-C85G3IA',
          lastModified: new Date(),
          changeFrequency: 'weekly',
          priority: 0.8,
    },
    {
          url: 'https://seefunnel.com/people/john-carlee-XPZCSY7',
          lastModified: new Date(),
          changeFrequency: 'weekly',
          priority: 0.8,
    },
    {
          url: 'https://seefunnel.com/people/katie-catlett-2DZT24O',
          lastModified: new Date(),
          changeFrequency: 'weekly',
          priority: 0.8,
    },
    {
          url: 'https://seefunnel.com/people/kenny-marion-TC5UN9Y',
          lastModified: new Date(),
          changeFrequency: 'weekly',
          priority: 0.8,
    },
    {
          url: 'https://seefunnel.com/people/kathryn-stansbury-Q5EJ0BU',
          lastModified: new Date(),
          changeFrequency: 'weekly',
          priority: 0.8,
    },
    {
          url: 'https://seefunnel.com/people/kathy-corsochase-99916AC',
          lastModified: new Date(),
          changeFrequency: 'weekly',
          priority: 0.8,
    },
    {
          url: 'https://seefunnel.com/people/john-ihnatolya-9BYVZ9Y',
          lastModified: new Date(),
          changeFrequency: 'weekly',
          priority: 0.8,
    },
    {
          url: 'https://seefunnel.com/people/kelly-dawson-PCUJ2MT',
          lastModified: new Date(),
          changeFrequency: 'weekly',
          priority: 0.8,
    },
    {
          url: 'https://seefunnel.com/people/joy-avila-1TAPSZ5',
          lastModified: new Date(),
          changeFrequency: 'weekly',
          priority: 0.8,
    },
    {
          url: 'https://seefunnel.com/people/justin-sebastian-0DY637T',
          lastModified: new Date(),
          changeFrequency: 'weekly',
          priority: 0.8,
    },
    {
          url: 'https://seefunnel.com/people/joe-lucas-24MER0Q',
          lastModified: new Date(),
          changeFrequency: 'weekly',
          priority: 0.8,
    },
    {
          url: 'https://seefunnel.com/people/kent-thompson-2RFQ25U',
          lastModified: new Date(),
          changeFrequency: 'weekly',
          priority: 0.8,
    },
    {
          url: 'https://seefunnel.com/people/jonathan-merryman-4F4M9XH',
          lastModified: new Date(),
          changeFrequency: 'weekly',
          priority: 0.8,
    },
    {
          url: 'https://seefunnel.com/people/john-friedl-ROVQ88V',
          lastModified: new Date(),
          changeFrequency: 'weekly',
          priority: 0.8,
    },
    {
          url: 'https://seefunnel.com/people/katherine-flowers-PCGJ7H5',
          lastModified: new Date(),
          changeFrequency: 'weekly',
          priority: 0.8,
    },
    {
          url: 'https://seefunnel.com/people/katherine-zyra-MQBFBUH',
          lastModified: new Date(),
          changeFrequency: 'weekly',
          priority: 0.8,
    },
    {
          url: 'https://seefunnel.com/people/joshua-conner-RB4QEEH',
          lastModified: new Date(),
          changeFrequency: 'weekly',
          priority: 0.8,
    },
    {
          url: 'https://seefunnel.com/people/jonathan-krecicki-3J3C98M',
          lastModified: new Date(),
          changeFrequency: 'weekly',
          priority: 0.8,
    },
    {
          url: 'https://seefunnel.com/people/josie-eatmon-W4T012D',
          lastModified: new Date(),
          changeFrequency: 'weekly',
          priority: 0.8,
    },
    {
          url: 'https://seefunnel.com/people/julie-paul-FQL9YYJ',
          lastModified: new Date(),
          changeFrequency: 'weekly',
          priority: 0.8,
    },
    {
          url: 'https://seefunnel.com/people/kelly-kuhn-1KRI1VC',
          lastModified: new Date(),
          changeFrequency: 'weekly',
          priority: 0.8,
    },
    {
          url: 'https://seefunnel.com/people/john-turner-REFED87',
          lastModified: new Date(),
          changeFrequency: 'weekly',
          priority: 0.8,
    },
    {
          url: 'https://seefunnel.com/people/katie-heineman-WAFUDK4',
          lastModified: new Date(),
          changeFrequency: 'weekly',
          priority: 0.8,
    },
    {
          url: 'https://seefunnel.com/people/kari-fotis-YTOGSMG',
          lastModified: new Date(),
          changeFrequency: 'weekly',
          priority: 0.8,
    },
    {
          url: 'https://seefunnel.com/people/karen-magge-C1J5GFZ',
          lastModified: new Date(),
          changeFrequency: 'weekly',
          priority: 0.8,
    },
    {
          url: 'https://seefunnel.com/people/kayla-wisecollins-4YTAHDJ',
          lastModified: new Date(),
          changeFrequency: 'weekly',
          priority: 0.8,
    },
    {
          url: 'https://seefunnel.com/people/kaileigh-west-KDV1PAL',
          lastModified: new Date(),
          changeFrequency: 'weekly',
          priority: 0.8,
    },
    {
          url: 'https://seefunnel.com/people/keith-flynn-QMNJ8PJ',
          lastModified: new Date(),
          changeFrequency: 'weekly',
          priority: 0.8,
    },
    {
          url: 'https://seefunnel.com/people/keith-wolf-IHPUDHM',
          lastModified: new Date(),
          changeFrequency: 'weekly',
          priority: 0.8,
    },
    {
          url: 'https://seefunnel.com/people/kenneth-bowers-JFZCONN',
          lastModified: new Date(),
          changeFrequency: 'weekly',
          priority: 0.8,
    },
    {
          url: 'https://seefunnel.com/people/kelsey-pratt-AV76A1O',
          lastModified: new Date(),
          changeFrequency: 'weekly',
          priority: 0.8,
    },
    {
          url: 'https://seefunnel.com/people/josette-roten-MBXALXC',
          lastModified: new Date(),
          changeFrequency: 'weekly',
          priority: 0.8,
    },
    {
          url: 'https://seefunnel.com/people/julie-sayers-7N0SI8G',
          lastModified: new Date(),
          changeFrequency: 'weekly',
          priority: 0.8,
    },
    {
          url: 'https://seefunnel.com/people/karen-holt-SYPO5VO',
          lastModified: new Date(),
          changeFrequency: 'weekly',
          priority: 0.8,
    },
    {
          url: 'https://seefunnel.com/people/john-constantelos-D4X11VU',
          lastModified: new Date(),
          changeFrequency: 'weekly',
          priority: 0.8,
    },
    {
          url: 'https://seefunnel.com/people/jon-agaton-HVC0FT7',
          lastModified: new Date(),
          changeFrequency: 'weekly',
          priority: 0.8,
    },
    {
          url: 'https://seefunnel.com/people/justine-wiggins-FQATWCO',
          lastModified: new Date(),
          changeFrequency: 'weekly',
          priority: 0.8,
    },
    {
          url: 'https://seefunnel.com/people/john-williamson-G3MZAOW',
          lastModified: new Date(),
          changeFrequency: 'weekly',
          priority: 0.8,
    },
    {
      url: 'https://seefunnel.com/people/kara-cox-NUOMA33',
      lastModified: new Date(),
      changeFrequency: 'weekly',
      priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/kathleen-marshall-ARU00OA',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/kearns-lowman-YA2PEQJ',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/john-strizzi-MGJFD6P',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/john-stamm-3H6LVSE',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/ken-perry-0U1Y5TN',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/keith-kelly-MBKM4D6',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/june-getzinger-PE633LJ',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/kelly-friesen-XVZ7REU',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/katrina-naylor-J71WS05',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/keith-parker-P6PAT46',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/katie-shelton-T9WZY0X',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/keisha-ragsdale-L4AVZ6G',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/kelly-palmatier-P2QSDEX',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/joseph-bridges-6LNHTA0',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/kelly-hunsucker-JCPCYMC',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/karthikeyan-ananthan-6OPAA07',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/kelly-holdbrooks-2T8GGLQ',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/julie-richardson-EWP28M6',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/kelsey-rogers-EOOL68X',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/julie-carrow-LXDZAG3',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/joyce-blum-733YMZ5',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/kendra-martin-7WVAINA',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/kelly-holland-QKCSKJZ',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/kelly-nichols-CLZU47V',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/kathy-giddings-ZZEAFC4',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/joe-ely-5K0KX5E',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/julius-scott-GXEX4TI',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/josh-farmer-TCE5RR4',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/jon-widdifield-WAU2UM7',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/johanna-mercado-WXO0NEG',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/kayleigh-cook-F1THI6A',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/kathryn-sweeney-I74Q1LY',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/joshua-mason-JC17RT2',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/kara-yates-9W7W4J6',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/katie-lamotta-X7L1BYP',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/joshua-schutt-Q74BF1I',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/jordan-newsome-NXOHVUQ',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/jorge-r-KR77P3N',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/jon-robb-ALF65DX',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/jonathan-burger-VO8IM96',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/jonathan-beam-XUN5QF5',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/jonathan-moore-T7K6LK9',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/joey-kitchens-VKCXIUD',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/john-gavigan-P8NNIAS',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/justin-king-TA1AGMW',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/karen-howell-TQIJAHC',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/joe-staples-T5RG3BV',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/kate-lague-ZCINQ49',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/joyce-burke-CMHXEFR',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/joseph-conde-4G5RD20',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/kenny-boggess-G6HBKTV',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/john-lynch-V9ISQXO',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/john-land-30DBSGK',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/kelly-katterhagen-0SZ45J9',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/jordan-pulido-6MN222X',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/kathy-simmons-2AMXTVG',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/katheryn-peterson-6Z56W5F',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/kaylan-mariano-F2YGSO4',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/kayce-johnson-HZILWIA',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/john-holmes-DF3AL7P',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/jordan-sprouse-F8C7F0J',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/kelli-stoup-UXWDBA7',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/keirstin-gavalas-VEK4N43',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/kathy-peters-GVR0569',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/joseph-kaloko-MQI8Z3H',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/john-mccally-2JKR4VI',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/kathryn-sears-Z8YMORE',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/kelly-talarczyk-AMSCX5E',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/joe-kosloski-JMU9ANL',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/karen-briley-1K8RFGZ',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/john-faison-R7HHCPD',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/judi-gibbons-99YIX16',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/katie-malloy-1IL4BQ0',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/josh-cloninger-GR3LEJB',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/jon-mcduffie-W6V6MWN',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/kate-sharpe-X6ORPJ4',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/joseph-bowers-HK1L5TW',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/kathy-farrell-V18I97U',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/kelli-sprague-OMDF538',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/karin-sullivan-2PO5IX4',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/joon-noh-MPX8C9M',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/julie-shewell-YN972HH',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/katie-rhodes-W105D82',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/johannah-sanchezadams-XVXO86N',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/kati-yuhas-NJLN6TU',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/kelly-andrews-51THO20',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/julie-walter-J1ZWM7D',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/kelleigh-smith-PM4GKAW',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/john-pena-330HBP0',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/jordan-alverson-YBEG56P',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/joni-delellis-LY9XE6T',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/joel-sullivan-OX1J6QD',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/joyce-garrett-NBNNZEO',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/kacy-gahagan-XB3Y1M4',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/keith-hobgood-QS1ZV39',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/katina-bryson-A892WJ7',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/kate-mayes-QF0ATRH',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/ken-kupfrian-3TP3RZM',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/john-george-NWP4QQ7',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/john-rocco-4K4AM2I',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/kacie-sullivan-LVGVFXI',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/kathy-hood-38C969Q',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/jonathan-henin-NDKGEYA',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/kelly-godbey-2ZITVHO',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/keith-williams-FZ6NX27',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/kelli-robinson-1ZMAQOE',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/joshua-wiley-7H3US64',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/kelly-smith-9PFWCWV',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/john-maselli-1PW6Z83',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/keith-huberman-WGFCBA0',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/ken-foster-0EDQVIF',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/kathleen-honaker-ROAVCGH',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/jonathan-ruble-XV8CBNP',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/john-robinson-288GS4Z',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/kelly-moravek-5P6TSIQ',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/kalli-sexton-XUBASMY',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/jon-latta-UL328AF',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/julie-harshaw-WJ1VO0V',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/kellyn-klug-K96IT2T',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/kent-geer-1WTTF89',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/kellodie-tassa-TJVX193',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/kenzie-miller-IHU4TYL',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/josh-spencer-G2IBQZD',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/karen-gray-5TP7IIP',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/kayla-dugger-1MUGS9C',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/john-brunick-S18YHU1',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/kaylee-campbell-761RL2T',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/keith-napier-JNH2UH1',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/josh-barnes-9I4OBML',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/kenneth-killion-7MJ6T6Z',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/kenny-chapman-EJVAB4Y',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/jordan-wilkins-XP160GP',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/karin-toomey-9D9GAJN',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/karen-mikami-UX14TJ0',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/julianna-roche-Z5GRMCY',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/julia-byron-000XRYS',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/justin-mcleymore-XJ330HQ',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/john-gibbings-UIROV94',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/john-byrne-FMV691X',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/josh-bassett-TGXZQYJ',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/joseph-noe-7QUX62N',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://www.seefunnel.com/view/149',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://www.seefunnel.com/view/150',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://www.seefunnel.com/view/151',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://www.seefunnel.com/view/152',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://www.seefunnel.com/view/154',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://www.seefunnel.com/view/155',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://www.seefunnel.com/view/156',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://www.seefunnel.com/view/157',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://www.seefunnel.com/view/158',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://www.seefunnel.com/view/159',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://www.seefunnel.com/view/160',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://www.seefunnel.com/view/161',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://www.seefunnel.com/view/162',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://www.seefunnel.com/view/163',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://www.seefunnel.com/view/164',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://www.seefunnel.com/view/165',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://www.seefunnel.com/view/166',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://www.seefunnel.com/view/167',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://www.seefunnel.com/view/168',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://www.seefunnel.com/view/169',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/katya-popa-Y9NDLV4',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/katie-richter-8X0QPFH',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/joseph-johnson-MPDKF16',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/joel-tracey-F28BX8J',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/julian-cook-U0HGM4M',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/katie-elsasser-8CFGYTN',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/keith-kilpatrick-S4D2MS8',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/julie-marr-VH4DJMI',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/john-cullen-5G2IEOJ',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/john-valeri-Q1LZ6W0',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/keith-rudemiller-F3J0JJA',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/kelly-koeninger-QCVUOJM',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/katherine-ehrlichman-4S3OECM',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/kathryn-briggs-5JAVMGH',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/jonathan-carie-FEOZ2WV',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/joseph-cooper-Z6S1NP8',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/kelly-honeycutt-S6X9U4S',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/kelly-parsons-3NERHK9',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/karen-walter-BZIE9P5',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/katie-shorter-Z8NV349',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/kathan-griscik-0EYM6CI',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/kenneth-marsh-78EBJ09',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/jonathan-robichaud-AJZSGQD',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/john-moore-IM2OUVE',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/jordan-atwell-5ZO2DX0',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/katheryn-jenifer-1E1PJKO',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/jordan-fuller-77C32XV',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/joy-giles-4I89O57',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/joshua-wheeler-3DUTE8G',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/john-mcauley-N9OJ5WB',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/kathryn-moffitt-0T9N6LK',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/kathy-lindenmayer-JBOIB78',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/katie-walsh-LMDKGXX',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/jonathan-saavedra-4IV11QE',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/kelly-langston-7XOBF7Q',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/katie-raine-SFY4AUJ',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/julian-carrington-P9FYXRH',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/karen-gould-2HGY6LD',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/joshua-canon-Z72BDES',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/kathryn-woods-CNGCMP8',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/katie-amor-19IWMFG',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/jon-mcwatters-6VADB7K',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/katy-rust-99OKO6F',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/kathy-walmer-3JP2KPJ',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/julie-fowler-8H2819J',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/kathryn-dorminey-L5DLHNY',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/joshua-snipes-XNOPZVU',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/katie-kutcher-XK45X71',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/john-loftin-I86VE9C',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/joe-daly-FTZQ806',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/kate-palmer-TKBS0RW',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/kathy-poteate-CEETSFG',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/kaylee-cutler-I2JSKCH',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/katy-turnbull-YK1NXBO',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/kate-short-6WAINPZ',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/john-shoemaker-R3Q20Z1',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/kennedy-fotheringham-TV9VO69',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/katura-jackson-2K880QL',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/kelly-stamey-W5RU5Q4',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/john-neuhauser-UMN3FZO',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/joey-ashley-BLHRS43',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/john-ruppe-PIS6AWK',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/kelton-hinton-VSSLISB',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/kara-carr-JKQDKJ9',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/katie-huffstetler-Y32D8MF',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/julie-thoman-IB82LRF',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/keith-stanis-1GQ8JZI',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/joe-godwin-E5UGKXP',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/juan-araujo-DT4EHQR',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/kelly-pierson-8DUZAGK',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/kelly-goldschmidt-JXT9DGC',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/jonathan-hesser-CRUT35W',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/john-toso-Y56WLQZ',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/john-garvilla-RXL0XNJ',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/karen-kus-F1K2EOV',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/jonathan-ibarra-1PPOKJO',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/kamalah-hill-SHDABAG',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/joshua-canter-BK8EO3N',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/karen-murphy-LU6D3NH',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/julee-triplett-ZJSLQ0S',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/kate-hazen-0J56YVY',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/kelly-garrity-XGLKPZ5',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/john-endres-6NY87HP',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/joe-maples-VI5RARK',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/joe-sumalnap-4XTUS3F',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/josh-sell-V1UQXMG',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/keely-rosenthal-HPD075N',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/joseph-gardner-Z3QQZGY',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/john-robins-UUOACJ4',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/julia-steffen-ZS6CMF7',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/josh-fowler-F57OUK5',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/kelly-sawyers-P68JK43',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/kathryn-yoakum-BCV8R0S',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/kathryn-hall-RGGFGWL',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/kara-dnp-HVZN8PA',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/kathy-burckley-YR28GSE',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/kelly-donaldson-MOJNNZJ',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/joshua-baker-XXKXJA4',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/julie-mckenzie-8SUU878',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/joey-bouchard-E6EDCXU',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/katie-garrett-A9GMWZN',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/katie-cornell-BI4UYUN',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/john-simeon-58D26CR',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/joey-siak-WDIBICN',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/jonathan-arthur-MPAKHX1',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/joe-rafferty-LPS6IMK',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/joshua-adkins-NK2ZUT8',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/karen-bradley-970MGOZ',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/katy-stewart-L6DT8KV',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/karen-blalock-2KTAI15',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/joshua-hoots-ZNFF9LV',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/ken-mowery-EMD3H4J',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/josh-bercovici-K58KJYR',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/john-bell-5XYZBXC',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/karissa-grasty-4D64K8W',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/kathleen-burkett-60QN360',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/katie-pleasant-HGXP1DH',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/jon-usrey-8NJEHQZ',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/kaleigh-blair-MUQMES7',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/kendall-frederick-H8UQ91M',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/jonathan-h-1PFA39Q',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/kathleen-brower-OP7B4L7',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/joy-ross-A0JHMWX',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/john-buchanan-FG0TG85',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/joy-neaves-B6PFWLP',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/julie-naegelen-UDOSKV6',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/keith-majeroni-99ZY6FG',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/jonathan-boggs-NJPKYEM',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/john-byrd-3ZT2XBA',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/jon-robertson-GC85RVC',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/katie-conrad-BT8OAZP',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/keith-neus-Z7WYVOT',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/jon-haese-OOE6DNS',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/jordan-galligan-FVW2K50',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/josh-watkins-CKF1L2X',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/kate-shoemaker-1W30WEV',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/kasey-eastland-SP67D08',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/katie-adams-RVUP91E',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/katy-cooper-9IFQ7Y8',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/kara-cannizzaro-OPWTRHY',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/kate-gavenus-MJP7AZ5',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/joy-parton-4T92190',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/kelsie-heermans-1LS9XWU',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/kara-o-X7VL30I',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/katie-bowen-L0TGHLJ',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/john-mikels-PUMINTW',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/katie-cooper-55EEZU9',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/kelley-amundson-FZAZS6X',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/ken-leibee-BIQJGI2',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/joshua-sheffield-SFK4LFR',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/josephine-brown-3O6HBM0',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/kathy-davis-8BPUIBL',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/jonathan-visconti-YMV90M4',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/karen-wingo-YNXO2B7',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/josh-noland-5JSQNRB',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/kathie-ray-DB8S4ZO',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/katie-gathings-P1KFUGH',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/julie-blair-UKA5ULL',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/ken-sparks-673G7X3',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/kathy-medlin-FWD7RKA',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/kelly-martin-0ZSIPTI',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/joey-trogdon-OLEYSE5',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/kelly-campbell-WY85XFY',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/kay-matthews-MB1D82X',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/judy-sawler-RAH27TE',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/kelly-turner-2434DVK',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/julie-wiggins-JRMSX5W',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/jon-mckivitz-ZY39KBZ',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/justin-reese-JHM2Q8B',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/kelley-bigger-Z2BGCMD',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/keith-koreng-WQPG4B8',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/julia-gwynette-NV511O3',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/katharine-daniels-HM4X8C5',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://seefunnel.com/people/katherine-gaydos-62NLZ4G',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://www.seefunnel.com/view/170',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
      {
            url: 'https://www.seefunnel.com/view/171',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
      },
          
    // {
    //   url: 'https://yourdomain.com/changes',
    //   lastModified: new Date(),
    //   changeFrequency: 'daily',
    //   priority: 0.8,
    // },
    // Add more routes dynamically if needed
    // Example with dynamic routes:
    // {
    //   url: 'https://yourdomain.com/products/product-slug',
    //   lastModified: new Date(),
    // }
  ]
}